preload = /home/kozyrevid/.config/hypr/wallpapers/enceladus.jpg
wallpaper {
    monitor = eDP-1
    path = /home/kozyrevid/.config/hypr/wallpapers/enceladus.jpg    
    fit_mode = cover
}
wallpaper {
    monitor = HDMI-A-1
    path = /home/kozyrevid/.config/hypr/wallpapers/enceladus.jpg    
    fit_mode = cover
}
